CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE formateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    promotion_id BIGINT NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE session_cours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    code VARCHAR(16) NOT NULL,
    promotion_id BIGINT NOT NULL,
    formateur_id BIGINT,
    ouverture_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fin_at TIMESTAMP WITH TIME ZONE,
    cloture_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_session_code UNIQUE (code),
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id),
    CONSTRAINT fk_session_formateur FOREIGN KEY (formateur_id) REFERENCES formateur(id),
    CONSTRAINT ck_session_expiration CHECK (expiration_at > ouverture_at),
    CONSTRAINT ck_session_fin CHECK (fin_at IS NULL OR fin_at >= ouverture_at),
    CONSTRAINT ck_session_cloture CHECK (cloture_at IS NULL OR fin_at IS NOT NULL)
);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    source VARCHAR(16) NOT NULL,
    marquee_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours(id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))
);

CREATE TABLE exercice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    lien VARCHAR(2048) NOT NULL,
    statut VARCHAR(40) NOT NULL,
    depose_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours(id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_DE_RELECTURE', 'EN_ATTENTE_SANS_RELECTEUR', 'RELU', 'EN_ATTENTE_VERROUILLE', 'RELU_VERROUILLE'))
);

CREATE TABLE relecture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL,
    relecteur_id BIGINT,
    note INTEGER,
    commentaire VARCHAR(4000),
    commencee_at TIMESTAMP WITH TIME ZONE,
    rendue_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice(id),
    CONSTRAINT fk_relecture_etudiant FOREIGN KEY (relecteur_id) REFERENCES etudiant(id),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note >= 0 AND note <= 20))
);

CREATE TABLE code_tentative (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etudiant_id BIGINT NOT NULL,
    tentatives INTEGER NOT NULL,
    bloque_jusqua TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_code_tentative_etudiant UNIQUE (etudiant_id),
    CONSTRAINT fk_code_tentative_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT ck_code_tentative_compteur CHECK (tentatives >= 0)
);

CREATE INDEX idx_etudiant_promotion ON etudiant(promotion_id);
CREATE INDEX idx_session_promotion ON session_cours(promotion_id);
CREATE INDEX idx_presence_session ON presence(session_id);
CREATE INDEX idx_presence_etudiant ON presence(etudiant_id);
CREATE INDEX idx_exercice_session ON exercice(session_id);
CREATE INDEX idx_exercice_etudiant ON exercice(etudiant_id);
CREATE INDEX idx_relecture_relecteur ON relecture(relecteur_id);
