-- Enveloppe étape 3 — « chaque exercice est relu par deux pairs différents, la note retenue
-- est la moyenne des deux ».
--
-- Q6 (« un seul relecteur par exercice ») est ANNULÉE. La contrainte qui la portait,
-- UNIQUE (exercice_id), devient UNIQUE (exercice_id, relecteur_id) : deux affectations au plus
-- par exercice, et jamais deux fois le même pair. La contrainte n'est pas supprimée, elle est
-- RELÂCHÉE d'un cran.
--
-- Cette migration est AJOUTÉE : V1 n'est pas modifiée. Elle est idempotente sur un schéma déjà
-- appliqué et elle préserve les données existantes.
--
-- POURQUOI RECRÉER LA TABLE ET NON ALTERER LA CONTRAINTE
-- H2 2.3 conserve l'index unique créé implicitement pour une contrainte UNIQUE même après
-- `ALTER TABLE ... DROP CONSTRAINT`, puis refuse `DROP INDEX` au motif que cet index
-- « appartient à une contrainte » (erreur 90085) ; le nom réel de la contrainte est introuvable
-- (erreur 90057). PostgreSQL n'a pas ce défaut et supprimerait l'index avec la contrainte.
-- Recréer la table est la seule forme qui donne le même schéma sur les DEUX bases, ce qui est
-- exigé par la consigne 2.2. `relecture` est une table feuille — aucune table n'y fait
-- référence — donc la recréation est sûre et peu coûteuse.

CREATE TABLE relecture_v4 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL,
    relecteur_id BIGINT,
    note INTEGER,
    commentaire VARCHAR(4000),
    commencee_at TIMESTAMP WITH TIME ZONE,
    rendue_at TIMESTAMP WITH TIME ZONE,
    -- Noms suffixés : H2 considère les noms de contraintes comme globaux et refuserait sinon
    -- de créer une contrainte portant le nom de celle de l'ancienne table, qui existe encore.
    -- Ils sont remis aux noms de V1 juste après le DROP TABLE, pour que le schéma final soit
    -- identique à ce que décrit D2.
    CONSTRAINT uk_relecture_exercice_relecteur_v4 UNIQUE (exercice_id, relecteur_id),
    CONSTRAINT fk_relecture_exercice_v4 FOREIGN KEY (exercice_id) REFERENCES exercice(id),
    CONSTRAINT fk_relecture_etudiant_v4 FOREIGN KEY (relecteur_id) REFERENCES etudiant(id),
    CONSTRAINT ck_relecture_note_v4 CHECK (note IS NULL OR (note >= 0 AND note <= 20))
);

-- Toutes les relectures existantes deviennent des affectations valides a une note pres.
-- Les identifiants ne sont PAS recopies : la nouvelle table redistribue les siens a partir de 1.
-- Reprendre les anciens `id` ferait repartir la sequence identitaire sur des valeurs deja
-- utilisees, et la premiere insertion suivante echouerait sur la cle primaire.
-- C'est sans consequence : `relecture` est une table feuille, aucune table n'y fait reference,
-- donc renumeroter ces cles ne casse aucune jointure.
INSERT INTO relecture_v4 (exercice_id, relecteur_id, note, commentaire, commencee_at, rendue_at)
SELECT exercice_id, relecteur_id, note, commentaire, commencee_at, rendue_at
FROM relecture;

DROP TABLE relecture;

ALTER TABLE relecture_v4 RENAME TO relecture;

ALTER TABLE relecture RENAME CONSTRAINT uk_relecture_exercice_relecteur_v4 TO uk_relecture_exercice_relecteur;
ALTER TABLE relecture RENAME CONSTRAINT fk_relecture_exercice_v4 TO fk_relecture_exercice;
ALTER TABLE relecture RENAME CONSTRAINT fk_relecture_etudiant_v4 TO fk_relecture_etudiant;
ALTER TABLE relecture RENAME CONSTRAINT ck_relecture_note_v4 TO ck_relecture_note;

-- Couvre l'agrégation de la moyenne et du caractère provisoire (EF17).
CREATE INDEX idx_relecture_exercice_rendue ON relecture (exercice_id, rendue_at);
